"""Parity test using fixtures generated by the official 3D-Speaker C++ Runtime."""

from __future__ import annotations

import os
from pathlib import Path

import numpy
import pytest

from mic.camplusplus import CamPlusPlusOnnx
from mic.campp_fbank import CamppFbank, CamppFbankConfig


@pytest.mark.real_adapter
def test_camplusplus_matches_official_runtime_golden_fixture() -> None:
    if os.environ.get("MIC_CAMPP_OFFICIAL_GOLDEN") != "1":
        pytest.skip("set MIC_CAMPP_OFFICIAL_GOLDEN=1 with controlled official fixtures")
    pcm = Path(os.environ["MIC_CAMPP_GOLDEN_PCM_PATH"]).read_bytes()
    expected_features = numpy.load(os.environ["MIC_CAMPP_GOLDEN_FBANK_PATH"])
    expected_embedding = numpy.load(os.environ["MIC_CAMPP_GOLDEN_EMBEDDING_PATH"])
    fbank_config = Path(os.environ["MIC_CAMPP_FBANK_CONFIG_PATH"])
    model = CamPlusPlusOnnx(
        Path(os.environ["MIC_CAMPP_MODEL_PATH"]),
        os.environ["MIC_CAMPP_MODEL_REVISION"],
        fbank_config,
    )

    actual_features = CamppFbank(CamppFbankConfig.load(fbank_config)).extract(pcm)
    actual_embedding = numpy.asarray(model.embed_pcm16le(pcm).values)
    expected_embedding = expected_embedding.reshape(-1)
    expected_embedding /= numpy.linalg.norm(expected_embedding)

    assert actual_features.shape == expected_features.shape
    assert numpy.allclose(actual_features, expected_features, rtol=1e-4, atol=1e-4)
    assert numpy.dot(actual_embedding, expected_embedding) >= 0.9999
